import * as Joi from 'joi';

export const envValidationSchema = Joi.object({
  NODE_ENV: Joi.string().valid('development', 'test', 'production').default('development'),
  PORT: Joi.number().default(4000),
  APP_NAME: Joi.string().default('Sidago CRM Backend'),
  APP_VERSION: Joi.string().default('1.0.0'),
  GLOBAL_PREFIX: Joi.string().default('api'),
  ALLOWED_ORIGINS: Joi.string().default('http://localhost:3000'),
  COOKIE_DOMAIN: Joi.string().default('localhost'),
  SWAGGER_ENABLED: Joi.boolean().default(true),
  SWAGGER_PATH: Joi.string().default('docs'),
  FRONTEND_URL: Joi.string().uri({ allowRelative: false }).default('http://localhost:3000'),
  DATABASE_URL: Joi.string().required(),
  DATABASE_ADMIN_URL: Joi.string().allow('', null),
  DATABASE_SSL: Joi.boolean().default(false),
  DATABASE_LOGGING: Joi.boolean().default(false),
  DATABASE_POOL_MIN: Joi.number().integer().min(1).default(2),
  DATABASE_POOL_MAX: Joi.number().integer().min(1).default(20),
  REDIS_URL: Joi.string().required(),
  REDIS_KEY_PREFIX: Joi.string().default('sidago:'),
  JWT_ACCESS_SECRET: Joi.string().min(16).required(),
  JWT_REFRESH_SECRET: Joi.string().min(16).required(),
  JWT_ACCESS_EXPIRES_IN: Joi.string().default('15m'),
  JWT_REFRESH_EXPIRES_IN: Joi.string().default('7d'),
  AUTH_BCRYPT_ROUNDS: Joi.number().integer().min(10).default(12),
  AUTH_MAX_FAILED_LOGINS: Joi.number().integer().min(1).default(5),
  AUTH_LOCK_MINUTES: Joi.number().integer().min(1).default(15),
  AUTH_VERIFICATION_EXPIRES_HOURS: Joi.number().integer().min(1).default(24),
  AUTH_RESET_PASSWORD_EXPIRES_MINUTES: Joi.number().integer().min(1).default(30),
  AUTH_SECURITY_ALERT_COOLDOWN_MINUTES: Joi.number().integer().min(1).default(15),
  AUTH_AVATAR_MAX_SIZE_BYTES: Joi.number().integer().min(1024).default(5242880),
  AUTH_SESSION_TOUCH_THROTTLE_SECONDS: Joi.number().integer().min(1).default(60),
  MAIL_HOST: Joi.string().allow('', null),
  MAIL_PORT: Joi.number().port().default(587),
  MAIL_SECURE: Joi.boolean().default(false),
  MAIL_USER: Joi.string().allow('', null),
  MAIL_PASS: Joi.string().allow('', null),
  MAIL_FROM: Joi.string().default('Sidago CRM <noreply@sidago.local>'),
  THROTTLE_TTL: Joi.number().integer().min(1).default(60),
  THROTTLE_LIMIT: Joi.number().integer().min(1).default(100),
  THROTTLE_AUTH_LIMIT: Joi.number().integer().min(1).default(10),
  QUEUE_PREFIX: Joi.string().default('sidago'),
  QUEUE_DEFAULT_ATTEMPTS: Joi.number().integer().min(1).default(3),
  QUEUE_DEFAULT_BACKOFF: Joi.number().integer().min(0).default(5000),
  QUEUE_CONCURRENCY: Joi.number().integer().min(1).default(5),
  LOG_FILE_MODE: Joi.string().valid('single', 'daily').default('single'),
  WS_CORS_ORIGIN: Joi.string().default('http://localhost:3000'),
  STORAGE_DRIVER: Joi.string().valid('local', 's3').default('local'),
  STORAGE_LOCAL_ROOT: Joi.string().default('storage/local'),
  STORAGE_LOCAL_BASE_URL: Joi.string().default('/storage/local'),
  STORAGE_S3_BUCKET: Joi.when('STORAGE_DRIVER', {
    is: 's3',
    then: Joi.string().required(),
    otherwise: Joi.string().allow('', null),
  }),
  STORAGE_S3_REGION: Joi.when('STORAGE_DRIVER', {
    is: 's3',
    then: Joi.string().required(),
    otherwise: Joi.string().allow('', null),
  }),
  STORAGE_S3_ENDPOINT: Joi.string().allow('', null),
  STORAGE_S3_PUBLIC_BASE_URL: Joi.string().allow('', null),
  STORAGE_S3_FORCE_PATH_STYLE: Joi.boolean().default(false),
  STORAGE_S3_PREFIX: Joi.string().allow('').default(''),
  STORAGE_S3_ACCESS_KEY_ID: Joi.when('STORAGE_DRIVER', {
    is: 's3',
    then: Joi.string().required(),
    otherwise: Joi.string().allow('', null),
  }),
  STORAGE_S3_SECRET_ACCESS_KEY: Joi.when('STORAGE_DRIVER', {
    is: 's3',
    then: Joi.string().required(),
    otherwise: Joi.string().allow('', null),
  }),
});
